ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
    TRAINER="Sivakumar" \
    DURATION="10HRS" \
    AUTHOR="joindevops"
RUN echo "Trainer is: ${TRAINER}, version is: ${version}"
CMD ["sleep", "200"]